[package]
name = "l3_batch_app_standalone"
type = "bin"
authors = []
compiler_version = ">=0.25.0"

[dependencies]
l3_types = { path = "../types" }
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v4.2.0-nightly.20260408", directory = "barretenberg/noir/bb_proof_verification" }
